
on:
  pull_request:

jobs:
  Guess:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"

      - run: |
          guess=$(cat guess.txt | tr -d '[:space:]')
          number="${{ secrets.number }}"

          if (( guess > number )); then
            echo "::error file=guess.txt,title=Incorrect::Hour number is too high!"
            exit 1
          elif (( guess < number )); then
            echo "::error file=guess.txt,title=Incorrect::Hour number is too low!"
            exit 1
          else
            echo "Correct!!!"
          fi

